### ISSUE TITLE
Package gabrieliuga/laravel-nova-mail-log at version  has a PHP requirement incompatible with your PHP version (7.3.13)

### ISSUE THREAD

**Issue by 4n70w4** [gabrieliuga/laravel-nova-mail-log#1]
Really need PHP >=7.4.0? Or is this a mistake?

**Comment by gabrieliuga** [comment]
This package depends on 2 others which have a 7.4 dependency gabrieliuga/laravel-nova-field-iframe and gabrieliuga/laravel-mail-log the latter one especially will receive functionality that will be developed for 7.4. I tend to develop towards the latest version, but I will look into it to see if I can lower the version to 7.3

**Comment by gabrieliuga** [comment]
Checkout the new version.
