### ISSUE TITLE
Readme unclear nor incomplete

### ISSUE THREAD

**Issue by renege** [gabrieliuga/laravel-nova-mail-log#3]
Hello,

Followed the instructions, but it does not do a thing.

And it is missing Screenshots

**Comment by gabrieliuga** [comment]
This package requires 2 other packages to function - follow the install instruction on each then proceed with the installation of nova-mail-log

1) https://github.com/gabrieliuga/laravel-mail-log
2) https://github.com/gabrieliuga/laravel-nova-field-iframe

I will make sure to include the instructions in the readme as soon as possible
