### ISSUE TITLE
Embeded images don't displayed

### ISSUE THREAD

**Issue by 4n70w4** [gabrieliuga/laravel-nova-mail-log#4]
In email templates I use `{{$message->embed(public_path('i/slojj-2.png'))}}` instead direct links to images.

```html
<img src="cid:446cd432636b61d9409244e6f3acd9d7@swift.generated" alt="" border="0" width="120px">
```

![image](https://user-images.githubusercontent.com/38257723/72900388-d4732400-3d38-11ea-978e-d94569510008.png)

**Comment by gabrieliuga** [comment]
Would it be possible to provide a full email template as example? Thanks

**Comment by 4n70w4** [comment]
```
<img src="{{$message->embed(public_path('i/sertifikat.png'))}}" alt=""  border="0" width="120px" />
```

https://laravel.com/docs/6.x/mail#inline-attachments


The same problem in https://github.com/jstoone/nova-mailman/issues/22

**Comment by gabrieliuga** [comment]
This was fixed in the related package: https://github.com/gabrieliuga/laravel-mail-log/releases/tag/v1.0.5
update and don't forget to run artisan migrate.
